FROM node:latest

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages


RUN npm install
RUN cd packages/db && npx prisma generate && ../..

RUN npm run build

CMD [ "npm","run","start-user-app" ]